import type { Metadata } from "next";
import {Providers} from "./providers";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/ui/Navbar";
import { ClerkProvider } from '@clerk/nextjs'
import Sidebar from "@/ui/Sidebar/Sidebar";
import LayoutWrapper from "@/ui/LayoutWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="flex flex-col min-h-dvh bg-ctp-base" suppressHydrationWarning>
        <body className={`flex flex-col grow ${inter.className}`}>
          <Providers>
            <Navbar />
            <LayoutWrapper>
              {children}
            </LayoutWrapper>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
