import type { Metadata } from "next";
import {Providers} from "./providers";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/ui/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full min-h-dvh bg-pink-200">
      <body className={`w-full ${inter.className}`}>
        <Providers>
          <Navbar />
          <main className="p-5">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
